# Generated by Django 4.1.7 on 2023-02-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('Tugas Harian', 'Tugas Harian'), ('Tugas Akhir', 'Tugas Akhir'), ('Ujian', 'Ujian')], max_length=20),
        ),
    ]
